import {
  CheckCircle2,
  Clock,
  RefreshCw,
  ShoppingBag,
  Wallet,
} from "lucide-react"
import type { Order, OrderTab, StatMetric } from "../types"

export const ORDERS_PAGE = {
  title: "Orders",
  subtitle: "Manage and fulfill customer orders.",
  searchPlaceholder: "Search by order ID, customer name or email...",
  totalCount: 1245,
  entityLabel: "orders",
  defaultPageSize: 8,
  pageSizeOptions: [8, 10, 25, 50],
} as const

export const ORDER_TABS: { label: string; value: OrderTab }[] = [
  { label: "All Orders", value: "all" },
  { label: "Pending", value: "pending" },
  { label: "Processing", value: "processing" },
  { label: "Shipped", value: "shipped" },
  { label: "Delivered", value: "delivered" },
  { label: "Cancelled", value: "cancelled" },
  { label: "Refunded", value: "refunded" },
]

export const ORDER_METRICS: StatMetric[] = [
  {
    id: "total",
    label: "Total Orders",
    value: "1,245",
    change: 14.2,
    icon: ShoppingBag,
    sparkline: [28, 30, 34, 33, 38, 40, 42, 45, 48, 52],
  },
  {
    id: "pending",
    label: "Pending",
    value: "112",
    change: -8.4,
    icon: Clock,
    sparkline: [80, 76, 72, 68, 64, 60, 58, 54, 50, 48],
  },
  {
    id: "processing",
    label: "Processing",
    value: "156",
    change: 12.7,
    icon: RefreshCw,
    sparkline: [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
  },
  {
    id: "completed",
    label: "Completed",
    value: "936",
    change: 18.3,
    icon: CheckCircle2,
    sparkline: [50, 52, 55, 58, 60, 63, 66, 70, 74, 78],
  },
  {
    id: "revenue",
    label: "Total Revenue",
    value: "PKR 2,458,750",
    change: 18.6,
    icon: Wallet,
    sparkline: [32, 38, 35, 44, 42, 50, 48, 58, 55, 62],
  },
]

const baseCustomer = {
  name: "Aisha Khan",
  email: "aisha.khan@email.com",
  phone: "+92 300 1234567",
}

const baseAddress = {
  line1: "42 Clifton Block 5",
  line2: "Apartment 12B",
  city: "Karachi, Sindh 75600",
  country: "Pakistan",
}

export const ORDERS: Order[] = [
  {
    id: "4821",
    orderNumber: "#4821",
    customer: baseCustomer,
    placedAt: "Jul 4, 2026",
    placedAtTime: "2:34 PM",
    source: "Placed via Website",
    status: "processing",
    total: "PKR 6,200",
    payment: {
      status: "paid",
      method: "JazzCash",
      transactionId: "JC-8847291034",
      paidAt: "Jul 4, 2026 · 2:35 PM",
    },
    fulfillment: "packing",
    shippingAddress: baseAddress,
    summary: {
      subtotal: "PKR 5,950",
      shipping: "PKR 150",
      tax: "PKR 100",
      total: "PKR 6,200",
    },
    items: [
      {
        id: "1",
        name: "Soft Blush",
        sku: "BEAU-FC-001",
        quantity: 1,
        price: "PKR 3,200",
        image: "/products/hero-product-placeholder.svg",
      },
      {
        id: "2",
        name: "Glass Lip",
        sku: "BEAU-LP-008",
        quantity: 1,
        price: "PKR 2,750",
        image: "/products/hero-product-placeholder.svg",
      },
    ],
  },
  {
    id: "4820",
    orderNumber: "#4820",
    customer: { name: "Sarah Ahmed", email: "sarah.ahmed@email.com", phone: "+92 321 9876543" },
    placedAt: "Jul 4, 2026",
    placedAtTime: "11:18 AM",
    source: "Placed via Website",
    status: "pending",
    total: "PKR 4,100",
    payment: { status: "pending", method: "Bank Transfer", transactionId: "—", paidAt: "—" },
    fulfillment: "unfulfilled",
    shippingAddress: { line1: "15 DHA Phase 6", city: "Lahore, Punjab 54000", country: "Pakistan" },
    summary: { subtotal: "PKR 4,100", shipping: "PKR 0", tax: "PKR 0", total: "PKR 4,100" },
    items: [
      { id: "1", name: "Veil Skin Tint", sku: "BEAU-FC-014", quantity: 1, price: "PKR 4,100", image: "/products/hero-product-placeholder.svg" },
    ],
  },
  {
    id: "4819",
    orderNumber: "#4819",
    customer: { name: "James Wilson", email: "j.wilson@email.com", phone: "+44 7700 900123" },
    placedAt: "Jul 3, 2026",
    placedAtTime: "6:42 PM",
    source: "Placed via Website",
    status: "shipped",
    total: "PKR 6,200",
    payment: { status: "paid", method: "Visa ·••• 4242", transactionId: "VISA-9928475610", paidAt: "Jul 3, 2026 · 6:43 PM" },
    fulfillment: "shipped",
    shippingAddress: { line1: "88 Park Lane", city: "London W1K 7TN", country: "United Kingdom" },
    summary: { subtotal: "PKR 5,900", shipping: "PKR 200", tax: "PKR 100", total: "PKR 6,200" },
    items: [
      { id: "1", name: "Soft Focus", sku: "BEAU-FC-005", quantity: 1, price: "PKR 3,450", image: "/products/hero-product-placeholder.svg" },
      { id: "2", name: "Glass Lip", sku: "BEAU-LP-008", quantity: 1, price: "PKR 2,450", image: "/products/hero-product-placeholder.svg" },
    ],
  },
  {
    id: "4818",
    orderNumber: "#4818",
    customer: { name: "Michael Chen", email: "m.chen@email.com", phone: "+1 415 555 0198" },
    placedAt: "Jul 3, 2026",
    placedAtTime: "3:15 PM",
    source: "Placed via Showroom",
    status: "delivered",
    total: "PKR 2,750",
    payment: { status: "paid", method: "Mastercard ·••• 8812", transactionId: "MC-7738291045", paidAt: "Jul 3, 2026 · 3:16 PM" },
    fulfillment: "delivered",
    shippingAddress: { line1: "500 Market Street", line2: "Suite 200", city: "San Francisco, CA 94105", country: "United States" },
    summary: { subtotal: "PKR 2,750", shipping: "PKR 0", tax: "PKR 0", total: "PKR 2,750" },
    items: [
      { id: "1", name: "Glass Lip", sku: "BEAU-LP-008", quantity: 1, price: "PKR 2,750", image: "/products/hero-product-placeholder.svg" },
    ],
  },
  {
    id: "4817",
    orderNumber: "#4817",
    customer: { name: "Emma Roberts", email: "emma.r@email.com", phone: "+61 412 345 678" },
    placedAt: "Jul 2, 2026",
    placedAtTime: "9:08 AM",
    source: "Placed via Website",
    status: "completed",
    total: "PKR 4,100",
    payment: { status: "paid", method: "PayPal", transactionId: "PP-5567890123", paidAt: "Jul 2, 2026 · 9:09 AM" },
    fulfillment: "delivered",
    shippingAddress: { line1: "22 Harbour View", city: "Sydney NSW 2000", country: "Australia" },
    summary: { subtotal: "PKR 4,100", shipping: "PKR 0", tax: "PKR 0", total: "PKR 4,100" },
    items: [
      { id: "1", name: "Veil Skin Tint", sku: "BEAU-FC-014", quantity: 1, price: "PKR 4,100", image: "/products/hero-product-placeholder.svg" },
    ],
  },
  {
    id: "4816",
    orderNumber: "#4816",
    customer: { name: "Fatima Ali", email: "fatima.ali@email.com", phone: "+92 333 4567890" },
    placedAt: "Jul 2, 2026",
    placedAtTime: "4:55 PM",
    source: "Placed via Website",
    status: "cancelled",
    total: "PKR 2,950",
    payment: { status: "refunded", method: "EasyPaisa", transactionId: "EP-3345678901", paidAt: "Jul 2, 2026 · 5:00 PM" },
    fulfillment: "cancelled",
    shippingAddress: { line1: "7 Gulberg III", city: "Lahore, Punjab 54660", country: "Pakistan" },
    summary: { subtotal: "PKR 2,950", shipping: "PKR 0", tax: "PKR 0", total: "PKR 2,950" },
    items: [
      { id: "1", name: "Lash Curl Mascara", sku: "BEAU-EY-011", quantity: 1, price: "PKR 2,950", image: "/products/hero-product-placeholder.svg" },
    ],
  },
  {
    id: "4815",
    orderNumber: "#4815",
    customer: { name: "David Park", email: "d.park@email.com", phone: "+82 10 1234 5678" },
    placedAt: "Jul 1, 2026",
    placedAtTime: "1:22 PM",
    source: "Placed via Website",
    status: "refunded",
    total: "PKR 3,200",
    payment: { status: "refunded", method: "Visa ·••• 9012", transactionId: "VISA-4456789012", paidAt: "Jul 1, 2026 · 1:23 PM" },
    fulfillment: "cancelled",
    shippingAddress: { line1: "101 Gangnam-daero", city: "Seoul 06028", country: "South Korea" },
    summary: { subtotal: "PKR 3,200", shipping: "PKR 0", tax: "PKR 0", total: "PKR 3,200" },
    items: [
      { id: "1", name: "Soft Blush", sku: "BEAU-FC-001", quantity: 1, price: "PKR 3,200", image: "/products/hero-product-placeholder.svg" },
    ],
  },
  {
    id: "4814",
    orderNumber: "#4814",
    customer: { name: "Nadia Hussain", email: "nadia.h@email.com", phone: "+92 345 6789012" },
    placedAt: "Jul 1, 2026",
    placedAtTime: "10:45 AM",
    source: "Placed via Website",
    status: "processing",
    total: "PKR 7,300",
    payment: { status: "paid", method: "JazzCash", transactionId: "JC-6678901234", paidAt: "Jul 1, 2026 · 10:46 AM" },
    fulfillment: "packing",
    shippingAddress: { line1: "33 Bahria Town Phase 8", city: "Islamabad 44000", country: "Pakistan" },
    summary: { subtotal: "PKR 6,950", shipping: "PKR 250", tax: "PKR 100", total: "PKR 7,300" },
    items: [
      { id: "1", name: "Soft Blush", sku: "BEAU-FC-001", quantity: 1, price: "PKR 3,200", image: "/products/hero-product-placeholder.svg" },
      { id: "2", name: "Veil Skin Tint", sku: "BEAU-FC-014", quantity: 1, price: "PKR 4,100", image: "/products/hero-product-placeholder.svg" },
    ],
  },
]

export const DEFAULT_SELECTED_ORDER_ID = "4821"
