import { AlertTriangle, CheckCircle2, Package, Wallet, XCircle } from "lucide-react"
import type { CatalogProduct, ProductFilterOption, ProductSummaryStat } from "../types"

export const PRODUCT_SUMMARY_STATS: ProductSummaryStat[] = [
  {
    id: "total",
    label: "Total Products",
    value: "265",
    change: 12.5,
    icon: Package,
  },
  {
    id: "active",
    label: "Active Products",
    value: "245",
    change: 10.3,
    icon: CheckCircle2,
  },
  {
    id: "out-of-stock",
    label: "Out of Stock",
    value: "4",
    change: -33.3,
    icon: XCircle,
  },
  {
    id: "low-stock",
    label: "Low Stock",
    value: "16",
    change: -20.0,
    icon: AlertTriangle,
  },
  {
    id: "total-value",
    label: "Total Value",
    value: "PKR 925,600",
    change: 15.8,
    icon: Wallet,
  },
]

export const CATEGORY_FILTERS: ProductFilterOption[] = [
  { label: "All Categories", value: "all" },
  { label: "Face", value: "face" },
  { label: "Eyes", value: "eyes" },
  { label: "Lips", value: "lips" },
  { label: "Skin", value: "skin" },
]

export const COLLECTION_FILTERS: ProductFilterOption[] = [
  { label: "All Collections", value: "all" },
  { label: "Everyday Glow", value: "everyday-glow" },
  { label: "Night Out", value: "night-out" },
  { label: "New Drop", value: "new-drop" },
  { label: "Best Sellers", value: "best-sellers" },
  { label: "Clean Skin", value: "clean-skin" },
]

export const STATUS_FILTERS: ProductFilterOption[] = [
  { label: "All Status", value: "all" },
  { label: "Active", value: "active" },
  { label: "Inactive", value: "inactive" },
  { label: "Low Stock", value: "low_stock" },
  { label: "Out of Stock", value: "out_of_stock" },
]

export const SORT_OPTIONS: ProductFilterOption[] = [
  { label: "Newest", value: "newest" },
  { label: "Oldest", value: "oldest" },
  { label: "Price: High to Low", value: "price-desc" },
  { label: "Price: Low to High", value: "price-asc" },
  { label: "Name A–Z", value: "name-asc" },
]

export const CATALOG_PRODUCTS: CatalogProduct[] = [
  {
    id: "1",
    name: "Soft Blush",
    collection: "Everyday Glow",
    sku: "BEAU-FC-001",
    category: "Face",
    price: "PKR 3,200",
    stock: 48,
    status: "active",
    visible: true,
    createdAt: "12 Jun 2026",
    image: "/products/hero-product-placeholder.svg",
  },
  {
    id: "2",
    name: "Veil Skin Tint",
    collection: "Best Sellers",
    sku: "BEAU-FC-014",
    category: "Face",
    price: "PKR 4,100",
    stock: 32,
    status: "active",
    visible: true,
    createdAt: "10 Jun 2026",
    image: "/products/hero-product-placeholder.svg",
  },
  {
    id: "3",
    name: "Glass Lip",
    collection: "Night Out",
    sku: "BEAU-LP-008",
    category: "Lips",
    price: "PKR 2,750",
    stock: 12,
    status: "low_stock",
    visible: true,
    createdAt: "8 Jun 2026",
    image: "/products/hero-product-placeholder.svg",
  },
  {
    id: "4",
    name: "Ink Liner",
    collection: "New Drop",
    sku: "BEAU-EY-022",
    category: "Eyes",
    price: "PKR 2,400",
    stock: 0,
    status: "out_of_stock",
    visible: false,
    createdAt: "5 Jun 2026",
    image: "/products/hero-product-placeholder.svg",
  },
  {
    id: "5",
    name: "Soft Focus",
    collection: "Everyday Glow",
    sku: "BEAU-FC-005",
    category: "Face",
    price: "PKR 3,450",
    stock: 56,
    status: "active",
    visible: true,
    createdAt: "3 Jun 2026",
    image: "/products/hero-product-placeholder.svg",
  },
  {
    id: "6",
    name: "Dew Serum",
    collection: "Clean Skin",
    sku: "BEAU-SK-007",
    category: "Skin",
    price: "PKR 3,800",
    stock: 24,
    status: "active",
    visible: true,
    createdAt: "1 Jun 2026",
    image: "/products/hero-product-placeholder.svg",
  },
  {
    id: "7",
    name: "Lash Curl Mascara",
    collection: "Night Out",
    sku: "BEAU-EY-011",
    category: "Eyes",
    price: "PKR 2,950",
    stock: 3,
    status: "low_stock",
    visible: true,
    createdAt: "28 May 2026",
    image: "/products/hero-product-placeholder.svg",
  },
  {
    id: "8",
    name: "Velvet Matte Lip",
    collection: "Best Sellers",
    sku: "BEAU-LP-019",
    category: "Lips",
    price: "PKR 2,650",
    stock: 18,
    status: "inactive",
    visible: false,
    createdAt: "25 May 2026",
    image: "/products/hero-product-placeholder.svg",
  },
]

export const PRODUCTS_PAGE = {
  title: "Products",
  subtitle: "Manage and organize your beauty products.",
  searchPlaceholder: "Search products by name, SKU, or category...",
  tableSearchPlaceholder: "Search in table...",
  totalCount: 265,
  pageSize: 8,
} as const
